In [41]:
# import libraries

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [42]:
# load the dataset

d_frame = pd.read_csv('DailyComments.csv')
d_frame

Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

In [43]:
# take the comment column for scheme implementation

corpus = d_frame['comments']

In [44]:
# Apply count vectorizer transformer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print("vectorized words")
print(vectorizer.get_feature_names())
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())


vectorized words
['are', 'bad', 'birthday', 'day', 'good', 'happening', 'having', 'hello', 'how', 'is', 'it', 'my', 'neither', 'nothing', 'or', 'really', 'so', 'special', 'super', 'there', 'today', 'you']
Identify Feature Words - Matrix View

[[1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0 2 1 0 0 0 1 1 1 0 0 0 0]
 [0 1 0 2 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0]]


In [45]:
df = pd.DataFrame({'text':corpus})

In [46]:
#check for positive words and negative words

df['positive2']= df.text.str.count('special')
df['positive3'] = df.text.str.count('Hello')
df['positive4'] = df.text.str.count('good')
df['negative1'] = df.text.str.count('bad')
df['negative2'] = df.text.str.count('nothing')
df['negative3'] = df.text.str.count('neither')

df['TotScore'] =  df.positive2 + df.positive3 + df.positive4 - df.negative1 - df.negative2 - df.negative3


print(df)

Z = sum(df['TotScore'])
print("")
print("Overall Score:  ",Z)

                                             text  positive2  positive3  \
0                             Hello, how are you?          0          1   
1                            Today is a good day!          0          0   
2  It's my birthday so it's a really special day!          1          0   
3       Today is neither a good day or a bad day!          0          0   
4                           I'm having a bad day.          0          0   
5       There' s nothing special happening today.          1          0   
6                      Today is a SUPER good day!          0          0   

   positive4  negative1  negative2  negative3  TotScore  
0          0          0          0          0         1  
1          1          0          0          0         1  
2          0          0          0          0         1  
3          1          1          0          1        -1  
4          0          1          0          0        -1  
5          0          0          1          0      

In [47]:
# Extra credit

new_df = pd.read_excel('tweet.xlsx')
new_df

id                                             Tweets
0  31963          i am thankful for freedom of speech.     
1  31964  i wish kpop aists never come in my country for...
2  31965  now people judge you by colour and english acc...
3  31966  have no idea who she is but what a stupid comm...
4  31967                 Admitted to Brown University, YAY!
5  31968                              Happy b'day to simeo.
6  31969                       Love to dance, hate to sing.

In [48]:
# using Tweets column

col_tweet = new_df['Tweets']
col_tweet

0            i am thankful for freedom of speech.     
1    i wish kpop aists never come in my country for...
2    now people judge you by colour and english acc...
3    have no idea who she is but what a stupid comm...
4                   Admitted to Brown University, YAY!
5                                Happy b'day to simeo.
6                         Love to dance, hate to sing.
Name: Tweets, dtype: object

In [49]:
# Apply count vectorizer transformer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(col_tweet)
print("vectorized words")
print(vectorizer.get_feature_names())
print("Identify Feature Words - Matrix View")
print("")
print( X.toarray())

vectorized words
['able', 'accent', 'admitted', 'aists', 'all', 'am', 'and', 'at', 'be', 'broke', 'brown', 'but', 'by', 'colour', 'come', 'comment', 'country', 'dance', 'day', 'death', 'english', 'for', 'freedom', 'happy', 'hate', 'have', 'idea', 'in', 'inviting', 'is', 'judge', 'kpop', 'love', 'make', 'my', 'never', 'no', 'not', 'now', 'of', 'people', 'perform', 'ppl', 'response', 'see', 'she', 'sideshow', 'simeo', 'sing', 'speech', 'stupid', 'thankful', 'them', 'to', 'university', 'was', 'what', 'who', 'wish', 'won', 'yay', 'you']
Identify Feature Words - Matrix View

[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 2 0 0 1 1
  0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 

In [50]:
# Implement scheme for categorizing positive and negative tweets

df = pd.DataFrame({'text':col_tweet})
df['positive1'] = df.text.str.count('thankful')
df['positive2']= df.text.str.count('Admitted')
df['positive3'] = df.text.str.count('Love')
df['positive4'] = df.text.str.count('Happy')
df['negative1'] = df.text.str.count('broke')
df['negative2'] = df.text.str.count('nothing')
df['negative3'] = df.text.str.count('stupid')
df['negative4'] = df.text.str.count('judge')
df['TotScore'] = df.positive1 + df.positive2 + df.positive3 + df.positive4 - df.negative1 - df.negative2 - df.negative3- df.negative4


print(df)

Z = sum(df['TotScore'])
print("")
print("Overall Score:  ",Z)

                                                text  positive1  positive2  \
0          i am thankful for freedom of speech.               1          0   
1  i wish kpop aists never come in my country for...          0          0   
2  now people judge you by colour and english acc...          0          0   
3  have no idea who she is but what a stupid comm...          0          0   
4                 Admitted to Brown University, YAY!          0          1   
5                              Happy b'day to simeo.          0          0   
6                       Love to dance, hate to sing.          0          0   

   positive3  positive4  negative1  negative2  negative3  negative4  TotScore  
0          0          0          0          0          0          0         1  
1          0          0          1          0          0          0        -1  
2          0          0          0          0          0          1        -1  
3          0          0          0          0          